// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf47TtY8TijVMigMDiiIhgB4m8qMxk_pA',
    appId: '1:429163352893:web:8219960d640931f5992b54',
    messagingSenderId: '429163352893',
    projectId: 'chat-app-flutter-demo',
    authDomain: 'chat-app-flutter-demo.firebaseapp.com',
    storageBucket: 'chat-app-flutter-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv1F3ssE_OImsFuGeQYwGLoxSyFnDtebI',
    appId: '1:429163352893:android:88bbddd38f24a819992b54',
    messagingSenderId: '429163352893',
    projectId: 'chat-app-flutter-demo',
    storageBucket: 'chat-app-flutter-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4tTy6Yy9dsdu06SzIftoK1tpzyuNufBo',
    appId: '1:429163352893:ios:f3102f6b45c2ce30992b54',
    messagingSenderId: '429163352893',
    projectId: 'chat-app-flutter-demo',
    storageBucket: 'chat-app-flutter-demo.appspot.com',
    iosBundleId: 'com.devblooming.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4tTy6Yy9dsdu06SzIftoK1tpzyuNufBo',
    appId: '1:429163352893:ios:9bd784a393988634992b54',
    messagingSenderId: '429163352893',
    projectId: 'chat-app-flutter-demo',
    storageBucket: 'chat-app-flutter-demo.appspot.com',
    iosBundleId: 'com.devblooming.chatApp.RunnerTests',
  );
}
